# This is a basic workflow to help you get started with Actions

name: FRONTSTORE_CI_TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the test branch
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /root/frontstore
            sudo git checkout test
            sudo git pull origin test
            docker-compose down --rmi all
            docker-compose up --build -d --remove-orphans
